#ifndef __INC_DM_VLXC__
#define __INC_DM_VLXC__

/*
 *
 Required DMPARAMS
 */
#define DM_VL_MAX_CACHE_SIZE    60

#define DM_VL_FORMAT  		"DM_VL_FORMAT"
#define DM_VL_FIELD_DOMINANCE   "DM_VL_FIELD_DOMINANCE"
#define DM_VL_TIMING  		"DM_VL_TIMING"

#define DM_VL_COLORSPACE 	"DM_VL_COLORSPACE"
#define DM_VL_PACKING 		"DM_VL_PACKING"

#define DM_VL_DIVO_LOOPBACK	"DM_DIVO_LOOPBACK"

#define DM_VL_RICE_PRECISION	"DM_VL_RICE_PRECISION"
#define DM_VL_RICE_SAMPLING	"DM_VL_RICE_SAMPLING"

#define DM_VL_BUFFER_CACHE_SIZE "DM_VL_BUFFER_CACHE_SIZE"

#define DM_DIVO_DEVICE		"DM_DIVO_DEVICE"
#endif
