#ifndef __MATH_H__
#define __MATH_H__

#include <internal/math_core.h>

/* Double-precision math functions */
__SGI_LIBC_USING_FROM_STD(acos)
__SGI_LIBC_USING_FROM_STD(asin)
__SGI_LIBC_USING_FROM_STD(atan)
__SGI_LIBC_USING_FROM_STD(atan2)
__SGI_LIBC_USING_FROM_STD(cos)
__SGI_LIBC_USING_FROM_STD(sin)
__SGI_LIBC_USING_FROM_STD(tan)
__SGI_LIBC_USING_FROM_STD(cosh)
__SGI_LIBC_USING_FROM_STD(sinh)
__SGI_LIBC_USING_FROM_STD(tanh)
__SGI_LIBC_USING_FROM_STD(exp)
__SGI_LIBC_USING_FROM_STD(frexp)
__SGI_LIBC_USING_FROM_STD(ldexp)
__SGI_LIBC_USING_FROM_STD(log)
__SGI_LIBC_USING_FROM_STD(log10)
__SGI_LIBC_USING_FROM_STD(modf)
__SGI_LIBC_USING_FROM_STD(pow)
__SGI_LIBC_USING_FROM_STD(sqrt)
__SGI_LIBC_USING_FROM_STD(ceil)
__SGI_LIBC_USING_FROM_STD(fabs)
__SGI_LIBC_USING_FROM_STD(floor)
__SGI_LIBC_USING_FROM_STD(fmod)

/* Single-precision math functions */
__SGI_LIBC_USING_FROM_STD(acosf)
__SGI_LIBC_USING_FROM_STD(asinf)
__SGI_LIBC_USING_FROM_STD(atanf)
__SGI_LIBC_USING_FROM_STD(atan2f)
__SGI_LIBC_USING_FROM_STD(cosf)
__SGI_LIBC_USING_FROM_STD(sinf)
__SGI_LIBC_USING_FROM_STD(tanf)
__SGI_LIBC_USING_FROM_STD(coshf)
__SGI_LIBC_USING_FROM_STD(sinhf)
__SGI_LIBC_USING_FROM_STD(tanhf)
__SGI_LIBC_USING_FROM_STD(expf)
#if (_MIPS_SIM==_MIPS_SIM_NABI32 || _MIPS_SIM==_MIPS_SIM_ABI64) && _SGIAPI
__SGI_LIBC_USING_FROM_STD(frexpf)
__SGI_LIBC_USING_FROM_STD(ldexpf)
#endif /* n32/64 */
__SGI_LIBC_USING_FROM_STD(logf)
__SGI_LIBC_USING_FROM_STD(log10f)
__SGI_LIBC_USING_FROM_STD(modff)
__SGI_LIBC_USING_FROM_STD(powf)
__SGI_LIBC_USING_FROM_STD(sqrtf)
__SGI_LIBC_USING_FROM_STD(ceilf)
__SGI_LIBC_USING_FROM_STD(fabsf)
__SGI_LIBC_USING_FROM_STD(floorf)
__SGI_LIBC_USING_FROM_STD(fmodf)

/* Quad-precision math functions */
#if (_MIPS_SIM==_MIPS_SIM_NABI32 || _MIPS_SIM==_MIPS_SIM_ABI64) && _SGIAPI
__SGI_LIBC_USING_FROM_STD(acosl)
__SGI_LIBC_USING_FROM_STD(asinl)
__SGI_LIBC_USING_FROM_STD(atanl)
__SGI_LIBC_USING_FROM_STD(atan2l)
__SGI_LIBC_USING_FROM_STD(cosl)
__SGI_LIBC_USING_FROM_STD(sinl)
__SGI_LIBC_USING_FROM_STD(tanl)
__SGI_LIBC_USING_FROM_STD(coshl)
__SGI_LIBC_USING_FROM_STD(sinhl)
__SGI_LIBC_USING_FROM_STD(tanhl)
__SGI_LIBC_USING_FROM_STD(expl)
__SGI_LIBC_USING_FROM_STD(frexpl)
__SGI_LIBC_USING_FROM_STD(ldexpl)
__SGI_LIBC_USING_FROM_STD(logl)
__SGI_LIBC_USING_FROM_STD(log10l)
__SGI_LIBC_USING_FROM_STD(modfl)
__SGI_LIBC_USING_FROM_STD(powl)
__SGI_LIBC_USING_FROM_STD(sqrtl)
__SGI_LIBC_USING_FROM_STD(ceill)
__SGI_LIBC_USING_FROM_STD(fabsl)
__SGI_LIBC_USING_FROM_STD(floorl)
__SGI_LIBC_USING_FROM_STD(fmodl)
#endif /* n32/64 */

/* abs, the one name added to <math.h> by the C++ standard */

__SGI_LIBC_USING_FROM_STD(abs)

#endif /* !__MATH_H__ */
