#ifndef __STDLIB_H__
#define __STDLIB_H__

#include <internal/stdlib_core.h>

__SGI_LIBC_USING_FROM_STD(size_t)
__SGI_LIBC_USING_FROM_STD(atof)
__SGI_LIBC_USING_FROM_STD(atoi)
__SGI_LIBC_USING_FROM_STD(atol)
__SGI_LIBC_USING_FROM_STD(strtod)
__SGI_LIBC_USING_FROM_STD(strtol)
__SGI_LIBC_USING_FROM_STD(strtoul)
__SGI_LIBC_USING_FROM_STD(rand)
__SGI_LIBC_USING_FROM_STD(srand)
__SGI_LIBC_USING_FROM_STD(calloc)
__SGI_LIBC_USING_FROM_STD(free)
__SGI_LIBC_USING_FROM_STD(malloc)
__SGI_LIBC_USING_FROM_STD(realloc)
__SGI_LIBC_USING_FROM_STD(abort)
__SGI_LIBC_USING_FROM_STD(atexit)
__SGI_LIBC_USING_FROM_STD(exit)
__SGI_LIBC_USING_FROM_STD(getenv)
__SGI_LIBC_USING_FROM_STD(system)
__SGI_LIBC_USING_FROM_STD(bsearch)
__SGI_LIBC_USING_FROM_STD(qsort)
__SGI_LIBC_USING_FROM_STD(abs)
__SGI_LIBC_USING_FROM_STD(div)
__SGI_LIBC_USING_FROM_STD(labs)
__SGI_LIBC_USING_FROM_STD(ldiv)
__SGI_LIBC_USING_FROM_STD(mbtowc)
__SGI_LIBC_USING_FROM_STD(mblen)
__SGI_LIBC_USING_FROM_STD(wctomb)
__SGI_LIBC_USING_FROM_STD(mbstowcs)
__SGI_LIBC_USING_FROM_STD(wcstombs)


#endif /* !__STDLIB_H__ */
