#ifndef __STRING_H__
#define __STRING_H__

#include <internal/string_core.h>

__SGI_LIBC_USING_FROM_STD(size_t)

__SGI_LIBC_USING_FROM_STD(memcpy)
__SGI_LIBC_USING_FROM_STD(memmove)
__SGI_LIBC_USING_FROM_STD(strcpy)
__SGI_LIBC_USING_FROM_STD(strncpy)
__SGI_LIBC_USING_FROM_STD(strcat)
__SGI_LIBC_USING_FROM_STD(strncat)
__SGI_LIBC_USING_FROM_STD(memccpy)
__SGI_LIBC_USING_FROM_STD(memcmp)
__SGI_LIBC_USING_FROM_STD(strcmp)
__SGI_LIBC_USING_FROM_STD(strcoll)
__SGI_LIBC_USING_FROM_STD(strncmp)
__SGI_LIBC_USING_FROM_STD(strxfrm)
__SGI_LIBC_USING_FROM_STD(memchr)
__SGI_LIBC_USING_FROM_STD(strchr)
__SGI_LIBC_USING_FROM_STD(strcspn)
__SGI_LIBC_USING_FROM_STD(strpbrk)
__SGI_LIBC_USING_FROM_STD(strrchr)
__SGI_LIBC_USING_FROM_STD(strspn)
__SGI_LIBC_USING_FROM_STD(strstr)
__SGI_LIBC_USING_FROM_STD(strtok)
__SGI_LIBC_USING_FROM_STD(memset)
__SGI_LIBC_USING_FROM_STD(strerror)
__SGI_LIBC_USING_FROM_STD(strlen)
#endif /* !__STRING_H__ */
